[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
intro_to_anchor_development = "LN6QNbzSeFWg4ggXDBpvwJBSCTaF5uphcFB7Axh3KrT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
