[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
intro_to_anchor_development = "ETfwDHLF5pMbPZyZKfxui1LBjiTRXztYGzTf6XEwqZa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
